services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd!0449
      MYSQL_DATABASE: snippetbox_db
      MYSQL_USER: snippetbox_user
      MYSQL_PASSWORD: Passw0rd!0449
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
