services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd!0449
      MYSQL_DATABASE: snippetbox_db
      MYSQL_USER: snippetbox_user
      MYSQL_PASSWORD: Passw0rd!0449
    ports:
      - "3306:3306"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --init-file /docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Passw0rd!0449
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes: {}
